import colorama
from colorama import Fore, Style
colorama.init() 
print('Colorama colors:')
print(Style.RESET_ALL + 'DEFAULT:  ' + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'BLACK:  ' + Fore.BLACK + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'BLUE:  ' + Fore.BLUE + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'CYAN:  ' + Fore.CYAN + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'GREEN:  ' + Fore.GREEN + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'LIGHTBLACK_EX:  ' + Fore.LIGHTBLACK_EX + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'LIGHTBLUE_EX:  ' + Fore.LIGHTBLUE_EX + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'LIGHTCYAN_EX:  ' + Fore.LIGHTCYAN_EX + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'LIGHTGREEN_EX:  ' + Fore.LIGHTGREEN_EX + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'LIGHTMAGENTA_EX:  ' + Fore.LIGHTMAGENTA_EX + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'LIGHTRED_EX:  ' + Fore.LIGHTRED_EX + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'LIGHTWHITE_EX:  ' + Fore.LIGHTWHITE_EX + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'LIGHTYELLOW_EX:  ' + Fore.LIGHTYELLOW_EX + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'MAGENTA:  ' + Fore.MAGENTA + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'RED:  ' + Fore.RED + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'WHITE:  ' + Fore.WHITE + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')
print(Style.RESET_ALL + 'YELLOW:  ' + Fore.YELLOW + Style.BRIGHT + 'BRIGHT ' + Style.DIM + 'DIM ' + Style.NORMAL + 'NORMAL')